export const sampleCategories = [
  { name: 'Breakfast & Snacks', slug: 'breakfast-snacks', icon: 'Sun', description: 'Traditional Jaffna hoppers, puttu, dosai & rolls' },
  { name: 'Tea & Beverages', slug: 'tea-beverages', icon: 'Coffee', description: 'Ceylon hot teas, Nestomalt & Nescafe' },
  { name: 'Curries', slug: 'curries', icon: 'Flame', description: 'Rich authentic Ceylon gravies & fried fish' },
  { name: 'Meals', slug: 'meals', icon: 'Utensils', description: 'Traditional rice meal platters with curries & sambol' },
  { name: 'Specials & Devils', slug: 'specials-devils', icon: 'Sparkles', description: 'Fiery devilled seafood, meat & omelettes' },
  { name: 'Biryani', slug: 'biryani', icon: 'Crown', description: 'Aromatic basmati Dum Biryani cooked with exotic spices' },
  { name: 'Rice Table', slug: 'rice-table', icon: 'Bowl', description: 'Wok-tossed fried rice (Half & Full portions)' },
  { name: 'Kottu Table', slug: 'kottu-table', icon: 'ChefHat', description: 'Sizzling shredded godamba roti kottu (Half & Full portions)' },
];

export const sampleFoods = [
  // TEA & BEVERAGES
  {
    name: 'Plain Tea',
    category: 'Tea & Beverages',
    price: 120,
    isAvailable: true,
    isVeg: true,
    description: 'Brewed pure Ceylon black tea served steaming hot.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '5 mins',
  },
  {
    name: 'Light Tea',
    category: 'Tea & Beverages',
    price: 140,
    isAvailable: true,
    isVeg: true,
    description: 'Mild Ceylon black tea infusion, light and aromatic.',
    imageUrl: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    prepTime: '5 mins',
  },
  {
    name: 'Nestomalt',
    category: 'Tea & Beverages',
    price: 220,
    isAvailable: true,
    isVeg: true,
    description: 'Warm wholesome malted beverage rich in essential vitamins.',
    imageUrl: 'https://images.unsplash.com/photo-1517578239113-b03992ba353c?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '5 mins',
  },
  {
    name: 'Nescafe',
    category: 'Tea & Beverages',
    price: 250,
    isAvailable: true,
    isVeg: true,
    description: 'Rich aromatic coffee blend served hot with frothy milk.',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '5 mins',
  },

  // BREAKFAST & SNACKS
  {
    name: 'Plain Appam',
    category: 'Breakfast & Snacks',
    price: 120,
    isAvailable: true,
    isVeg: true,
    description: 'Bowl-shaped coconut milk hopper with crispy golden edges.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '10 mins',
  },
  {
    name: 'Paal Appam',
    category: 'Breakfast & Snacks',
    price: 180,
    isAvailable: true,
    isVeg: true,
    description: 'Sweet coconut cream hopper infused with cardamom aroma.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '10 mins',
  },
  {
    name: 'Egg Appam',
    category: 'Breakfast & Snacks',
    price: 250,
    isAvailable: true,
    isVeg: false,
    description: 'Golden hopper with a soft poached egg cooked at the center.',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '12 mins',
  },
  {
    name: 'String Hopper',
    category: 'Breakfast & Snacks',
    price: 250,
    isAvailable: true,
    isVeg: true,
    description: 'Steamed rice noodle nests served with pol sambol and dahl curry (Set of 10).',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '12 mins',
  },
  {
    name: 'Puttu',
    category: 'Breakfast & Snacks',
    price: 280,
    isAvailable: true,
    isVeg: true,
    description: 'Steamed rice flour and coconut cylinders served with spiced curry.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '15 mins',
  },
  {
    name: 'Dosai',
    category: 'Breakfast & Snacks',
    price: 250,
    isAvailable: true,
    isVeg: true,
    description: 'Crispy paper thin fermented rice crepe served with coconut chutney & sambar.',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '10 mins',
  },
  {
    name: 'Parotta',
    category: 'Breakfast & Snacks',
    price: 150,
    isAvailable: true,
    isVeg: true,
    description: 'Flaky layered griddled roti toasted golden brown.',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '8 mins',
  },
  {
    name: 'Roli / Roll',
    category: 'Breakfast & Snacks',
    price: 120,
    isAvailable: true,
    isVeg: true,
    description: 'Crispy fried classic pastry roll packed with savory stuffing.',
    imageUrl: 'https://images.unsplash.com/photo-1606471191009-63994c53433b?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    prepTime: '5 mins',
  },
  {
    name: 'Veg Roll',
    category: 'Breakfast & Snacks',
    price: 140,
    isAvailable: true,
    isVeg: true,
    description: 'Crunchy breaded roll stuffed with seasoned spiced vegetables.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    rating: 4.65,
    prepTime: '8 mins',
  },
  {
    name: 'Egg Roll',
    category: 'Breakfast & Snacks',
    price: 180,
    isAvailable: true,
    isVeg: false,
    description: 'Crispy roll stuffed with spiced potato filling and hard-boiled egg.',
    imageUrl: 'https://images.unsplash.com/photo-1606471191009-63994c53433b?auto=format&fit=crop&w=800&q=80',
    rating: 4.75,
    prepTime: '8 mins',
  },
  {
    name: 'Samosa',
    category: 'Breakfast & Snacks',
    price: 120,
    isAvailable: true,
    isVeg: true,
    description: 'Golden fried triangular pastry filled with spiced potato and pea filling.',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '5 mins',
  },
  {
    name: 'Vadai',
    category: 'Breakfast & Snacks',
    price: 100,
    isAvailable: true,
    isVeg: true,
    description: 'Traditional crunchy lentil fritter packed with onion and green chili.',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    prepTime: '5 mins',
  },
  {
    name: 'Methu Vadi / Ulundu Vadai',
    category: 'Breakfast & Snacks',
    price: 120,
    isAvailable: true,
    isVeg: true,
    description: 'Crispy black gram doughnut fritter seasoned with cumin and curry leaves.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '5 mins',
  },
  {
    name: 'Vayppan',
    category: 'Breakfast & Snacks',
    price: 150,
    isAvailable: true,
    isVeg: true,
    description: 'Traditional sweet banana fritter snack fried crisp on the outside.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.75,
    prepTime: '8 mins',
  },

  // CURRIES
  {
    name: 'Chicken Curry',
    category: 'Curries',
    price: 850,
    isAvailable: true,
    isVeg: false,
    description: 'Tender chicken slow-cooked in rich dark roasted Ceylon curry spices.',
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '20 mins',
  },
  {
    name: 'Beef Curry',
    category: 'Curries',
    price: 950,
    isAvailable: true,
    isVeg: false,
    description: 'Succulent beef simmered with thick spicy Ceylon gravy.',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '22 mins',
  },
  {
    name: 'Mutton Curry',
    category: 'Curries',
    price: 1400,
    isAvailable: true,
    isVeg: false,
    description: 'Premium tender mutton cooked in clay pot curry spices.',
    imageUrl: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '25 mins',
  },
  {
    name: 'Fish Curry',
    category: 'Curries',
    price: 750,
    isAvailable: true,
    isVeg: false,
    description: 'Fresh ocean fish simmered in tangy goraka and coconut curry.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '20 mins',
  },
  {
    name: 'Fish Fry',
    category: 'Curries',
    price: 650,
    isAvailable: true,
    isVeg: false,
    description: 'Pan-fried sea fish marinated in red chili paste and spices.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '15 mins',
  },

  // MEALS
  {
    name: 'Veg Meal',
    category: 'Meals',
    price: 650,
    isAvailable: true,
    isVeg: true,
    description: 'Traditional Sri Lankan rice platter with dahl, 4 veggie curries & papadam.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '15 mins',
  },
  {
    name: 'Fish Meal',
    category: 'Meals',
    price: 850,
    isAvailable: true,
    isVeg: false,
    description: 'Authentic rice thali served with sea fish curry, vegetable sides & sambol.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Meal',
    category: 'Meals',
    price: 750,
    isAvailable: true,
    isVeg: false,
    description: 'Rice meal platter featuring spiced hard-boiled eggs in red curry gravy.',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Meal',
    category: 'Meals',
    price: 950,
    isAvailable: true,
    isVeg: false,
    description: 'Full rice thali served with roasted chicken curry & 4 vegetable curries.',
    imageUrl: 'https://images.unsplash.com/photo-1617692855027-33b14f061079?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '15 mins',
  },
  {
    name: 'Beef Meal',
    category: 'Meals',
    price: 1050,
    isAvailable: true,
    isVeg: false,
    description: 'Hearty rice platter served with dark spicy beef curry and sides.',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.88,
    prepTime: '15 mins',
  },
  {
    name: 'Mulisa Meal (Mutton Special Meal)',
    category: 'Meals',
    price: 1450,
    isAvailable: true,
    isVeg: false,
    description: 'Pearl Hotel Royal Special banana-leaf thali served with tender mutton curry.',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80',
    rating: 4.98,
    prepTime: '20 mins',
  },

  // SPECIALS & DEVILS
  {
    name: 'Omelette',
    category: 'Specials & Devils',
    price: 250,
    isAvailable: true,
    isVeg: false,
    description: 'Fluffy double-egg omelette pan-fried with onions, tomatoes & green chili.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '10 mins',
  },
  {
    name: 'Chicken Devil',
    category: 'Specials & Devils',
    price: 1350,
    isAvailable: true,
    isVeg: false,
    description: 'Crispy fried chicken chunks sautéed in sweet & spicy chili pepper sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '18 mins',
  },
  {
    name: 'Beef Devil',
    category: 'Specials & Devils',
    price: 1450,
    isAvailable: true,
    isVeg: false,
    description: 'Seared beef strips tossed in fiery tomato-chili reduction with bell peppers.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Prawn Devil',
    category: 'Specials & Devils',
    price: 1650,
    isAvailable: true,
    isVeg: false,
    description: 'Juicy jumbo ocean prawns tossed in hot devilled chili glaze.',
    imageUrl: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=800&q=80',
    rating: 4.96,
    prepTime: '20 mins',
  },
  {
    name: 'Squid Devil',
    category: 'Specials & Devils',
    price: 1550,
    isAvailable: true,
    isVeg: false,
    description: 'Tender ocean squid rings stir-fried with capsicum, onions & spicy pepper sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },

  // BIRYANI
  {
    name: 'Egg Biryani',
    category: 'Biryani',
    price: 950,
    isAvailable: true,
    isVeg: false,
    description: 'Fragrant basmati rice slow-cooked with exotic biryani spices & boiled egg.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '20 mins',
  },
  {
    name: 'Chicken Biryani',
    category: 'Biryani',
    price: 1450,
    isAvailable: true,
    isVeg: false,
    description: 'Royal Dum Biryani layered with succulent spiced chicken leg & boiled egg.',
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    rating: 4.98,
    prepTime: '22 mins',
  },
  {
    name: 'Beef Biryani',
    category: 'Biryani',
    price: 1550,
    isAvailable: true,
    isVeg: false,
    description: 'Spiced basmati biryani cooked with tender beef chunks & caramelized onions.',
    imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '25 mins',
  },
  {
    name: 'Mutton Biryani',
    category: 'Biryani',
    price: 1850,
    isAvailable: true,
    isVeg: false,
    description: 'Supreme Dum Biryani cooked with tender mutton pieces, mint & raita.',
    imageUrl: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=800&q=80',
    rating: 4.99,
    prepTime: '25 mins',
  },

  // RICE TABLE (Half & Full options)
  {
    name: 'Veg Rice (Full Portion)',
    category: 'Rice Table',
    price: 750,
    isAvailable: true,
    isVeg: true,
    description: 'Wok-tossed basmati fried rice with fresh vegetables & soy glaze (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '15 mins',
  },
  {
    name: 'Veg Rice (Half Portion)',
    category: 'Rice Table',
    price: 500,
    isAvailable: true,
    isVeg: true,
    description: 'Half portion wok-tossed vegetable fried rice.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    rating: 4.75,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Rice (Full Portion)',
    category: 'Rice Table',
    price: 850,
    isAvailable: true,
    isVeg: false,
    description: 'Savory fried rice scrambled with fresh farm eggs (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Rice (Full Portion)',
    category: 'Rice Table',
    price: 1100,
    isAvailable: true,
    isVeg: false,
    description: 'Signature fried rice tossed with juicy marinated chicken pieces (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '18 mins',
  },
  {
    name: 'Beef Rice (Full Portion)',
    category: 'Rice Table',
    price: 1250,
    isAvailable: true,
    isVeg: false,
    description: 'Wok-fried rice with tender spiced beef cuts & green onions (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Prawn Rice (Full Portion)',
    category: 'Rice Table',
    price: 1500,
    isAvailable: true,
    isVeg: false,
    description: 'Aromatic fried rice loaded with ocean prawns (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '20 mins',
  },
  {
    name: 'Squid Rice (Full Portion)',
    category: 'Rice Table',
    price: 1450,
    isAvailable: true,
    isVeg: false,
    description: 'Seafood fried rice with seasoned squid rings (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Mix Rice (Full Portion)',
    category: 'Rice Table',
    price: 1650,
    isAvailable: true,
    isVeg: false,
    description: 'Ultimate mixed fried rice loaded with chicken, beef, prawns & egg (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    rating: 4.98,
    prepTime: '20 mins',
  },

  // KOTTU TABLE (Half & Full options)
  {
    name: 'Veg Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 800,
    isAvailable: true,
    isVeg: true,
    description: 'Shredded godamba roti stir-fried with vegetables & spices (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 950,
    isAvailable: true,
    isVeg: false,
    description: 'Chopped roti cooked on iron flat top with scrambled egg and curry (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1200,
    isAvailable: true,
    isVeg: false,
    description: 'Classic Sri Lankan street food chopped roti with roasted chicken & curry gravy (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    rating: 4.99,
    prepTime: '18 mins',
  },
  {
    name: 'Beef Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1350,
    isAvailable: true,
    isVeg: false,
    description: 'Spicy chopped roti with tender beef, egg & rich beef gravy (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '20 mins',
  },
  {
    name: 'Prawn Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1600,
    isAvailable: true,
    isVeg: false,
    description: 'Seafood special kottu chopped with fresh prawns, egg & capsicum (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '20 mins',
  },
  {
    name: 'Squid Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1500,
    isAvailable: true,
    isVeg: false,
    description: 'Tender squid rings chopped with roti, veggies & seafood sauce (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Mix Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1800,
    isAvailable: true,
    isVeg: false,
    description: 'The supreme royal kottu combining chicken, beef, prawns & egg (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    rating: 4.99,
    prepTime: '22 mins',
  },
];
