export const sampleCategories = [
  { name: 'Breakfast & Snacks', slug: 'breakfast-snacks', icon: 'Sun', description: 'Traditional Jaffna appams, puttu, dosai, parotta, idiyappam & rolls' },
  { name: 'Tea & Beverages', slug: 'tea-beverages', icon: 'Coffee', description: 'Ceylon hot teas, Nestomalt & Nescafe' },
  { name: 'Sodas & Water Bottles', slug: 'sodas-water-bottles', icon: 'CupSoda', description: 'Cold Coca-Cola, Sprite, Fanta sodas & mineral water bottles' },
  { name: 'Curries', slug: 'curries', icon: 'Flame', description: 'Rich authentic Ceylon gravies & fried sea fish' },
  { name: 'Meals', slug: 'meals', icon: 'Utensils', description: 'Traditional rice meal platters with curries & sambol' },
  { name: 'Specials & Devils', slug: 'specials-devils', icon: 'Sparkles', description: 'Fiery devilled seafood, meat & omelettes' },
  { name: 'Biryani', slug: 'biryani', icon: 'Crown', description: 'Aromatic Basmati Dum Biryani with exotic spices' },
  { name: 'Rice Table', slug: 'rice-table', icon: 'Bowl', description: 'Wok-tossed fried rice (Half & Full portions)' },
  { name: 'Kottu Table', slug: 'kottu-table', icon: 'ChefHat', description: 'Sizzling shredded godamba roti kottu (Half & Full portions)' },
];

export const sampleFoods = [
  // TEA & BEVERAGES
  {
    name: 'Plain Tea',
    category: 'Tea & Beverages',
    price: 50,
    isAvailable: true,
    isVeg: true,
    description: 'Brewed pure Ceylon black tea served steaming hot.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '5 mins',
  },
  {
    name: 'Tea',
    category: 'Tea & Beverages',
    price: 120,
    isAvailable: true,
    isVeg: true,
    description: 'Rich Ceylon black tea brewed with fresh milk and subtle sweetness.',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '5 mins',
  },
  {
    name: 'Nestomalt Tea',
    category: 'Tea & Beverages',
    price: 140,
    isAvailable: true,
    isVeg: true,
    description: 'Warm wholesome Nestomalt malted beverage rich in essential vitamins.',
    imageUrl: '/images/nestomalt_tea.png',
    rating: 4.85,
    prepTime: '5 mins',
  },
  {
    name: 'Nescafe',
    category: 'Tea & Beverages',
    price: 140,
    isAvailable: true,
    isVeg: true,
    description: 'Rich aromatic Nescafe coffee blend served hot with milk.',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '5 mins',
  },

  // SODAS & WATER BOTTLES (BRANDED SODAS & WATER)
  {
    name: 'Mineral Water Bottle (500ml)',
    category: 'Sodas & Water Bottles',
    price: 120,
    isAvailable: true,
    isVeg: true,
    description: 'Chilled pure Sri Lankan mineral bottled drinking water (500ml).',
    imageUrl: '/images/water_bottles_cooler.png',
    rating: 4.9,
    prepTime: '1 min',
  },
  {
    name: 'Mineral Water Bottle (1.5L)',
    category: 'Sodas & Water Bottles',
    price: 180,
    isAvailable: true,
    isVeg: true,
    description: 'Large family-size chilled pure Sri Lankan bottled mineral drinking water (1.5L).',
    imageUrl: '/images/water_bottles_cooler.png',
    rating: 4.9,
    prepTime: '1 min',
  },
  {
    name: 'Glass Bottle Soft Drink (300ml)',
    category: 'Sodas & Water Bottles',
    price: 100,
    isAvailable: true,
    isVeg: true,
    description: 'Chilled classic glass bottle Coca-Cola / Sprite / Fanta (300ml).',
    imageUrl: '/images/soda_cooler_real.png',
    rating: 4.95,
    prepTime: '1 min',
  },
  {
    name: 'Soft Drink PET Bottle (400ml - 750ml)',
    category: 'Sodas & Water Bottles',
    price: 400,
    isAvailable: true,
    isVeg: true,
    description: 'Chilled Coca-Cola, Sprite, or Fanta PET bottle drink.',
    imageUrl: '/images/soda_cooler_real.png',
    rating: 4.9,
    prepTime: '1 min',
  },
  {
    name: 'Large Soft Drink Bottle (1.5L)',
    category: 'Sodas & Water Bottles',
    price: 388,
    isAvailable: true,
    isVeg: true,
    description: 'Large 1.5L chilled Coca-Cola / Sprite PET bottle.',
    imageUrl: '/images/soda_cooler_real.png',
    rating: 4.9,
    prepTime: '1 min',
  },

  // BREAKFAST & SNACKS (INCLUDING DEDICATED APPAMS / HOPPERS)
  {
    name: 'Plain Appam',
    category: 'Breakfast & Snacks',
    price: 50,
    isAvailable: true,
    isVeg: true,
    description: 'Crispy golden bowl-shaped coconut milk hopper with soft center.',
    imageUrl: '/images/appam_plain.png',
    rating: 4.95,
    prepTime: '8 mins',
  },
  {
    name: 'Paal Appam',
    category: 'Breakfast & Snacks',
    price: 70,
    isAvailable: true,
    isVeg: true,
    description: 'Sweet coconut cream hopper infused with cardamom aroma.',
    imageUrl: '/images/appam_paal.png',
    rating: 4.92,
    prepTime: '8 mins',
  },
  {
    name: 'Egg Appam',
    category: 'Breakfast & Snacks',
    price: 90,
    isAvailable: true,
    isVeg: false,
    description: 'Golden bowl hopper with a soft poached farm egg cooked at the center.',
    imageUrl: '/images/appam_egg.png',
    rating: 4.98,
    prepTime: '10 mins',
  },
  {
    name: 'Idiyappam / String Hopper (Per Piece)',
    category: 'Breakfast & Snacks',
    price: 20,
    isAvailable: true,
    isVeg: true,
    description: 'Soft steamed rice flour string hoppers served fresh.',
    imageUrl: '/images/idiyappam_real.jpg',
    rating: 4.9,
    prepTime: '5 mins',
  },
  {
    name: 'Dosai',
    category: 'Breakfast & Snacks',
    price: 60,
    isAvailable: true,
    isVeg: true,
    description: 'Crispy golden fermented rice & lentil crepe served with chutney & sambar.',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '10 mins',
  },
  {
    name: 'Parotta',
    category: 'Breakfast & Snacks',
    price: 60,
    isAvailable: true,
    isVeg: true,
    description: 'Flaky layered griddled flatbread toasted golden brown on the tawa.',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '8 mins',
  },
  {
    name: 'Vayppan (Sweet Banana Fritter)',
    category: 'Breakfast & Snacks',
    price: 60,
    isAvailable: true,
    isVeg: true,
    description: 'Traditional Ceylon sweet ripe banana fritter crisp on the outside.',
    imageUrl: '/images/vayppan_real.jpg',
    rating: 4.8,
    prepTime: '5 mins',
  },
  {
    name: 'Vadai',
    category: 'Breakfast & Snacks',
    price: 70,
    isAvailable: true,
    isVeg: true,
    description: 'Crunchy savory lentil fritter packed with onions and spicy green chillies.',
    imageUrl: '/images/vadai_crispy.png',
    rating: 4.8,
    prepTime: '5 mins',
  },
  {
    name: 'Roll',
    category: 'Breakfast & Snacks',
    price: 80,
    isAvailable: true,
    isVeg: true,
    description: 'Crispy breaded short-eat pastry roll stuffed with delicious filling.',
    imageUrl: '/images/short_eat_roll.png',
    rating: 4.75,
    prepTime: '5 mins',
  },
  {
    name: 'Vegetable Roti',
    category: 'Breakfast & Snacks',
    price: 100,
    isAvailable: true,
    isVeg: true,
    description: 'Griddled flatbread stuffed with spiced curried potato and vegetables.',
    imageUrl: '/images/vegetable_roti_real.jpg',
    rating: 4.85,
    prepTime: '8 mins',
  },
  {
    name: 'Samosa',
    category: 'Breakfast & Snacks',
    price: 100,
    isAvailable: true,
    isVeg: true,
    description: 'Deep-fried triangular pastry loaded with spiced potato and green peas.',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '5 mins',
  },
  {
    name: 'Puttu',
    category: 'Breakfast & Snacks',
    price: 150,
    isAvailable: true,
    isVeg: true,
    description: 'Steamed rice flour and freshly grated coconut cylinder.',
    imageUrl: '/images/puttu_real.jpg',
    rating: 4.85,
    prepTime: '12 mins',
  },
  {
    name: 'Egg Roti',
    category: 'Breakfast & Snacks',
    price: 150,
    isAvailable: true,
    isVeg: false,
    description: 'Tawa-toasted flatbread stuffed with fresh farm egg and onions.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '10 mins',
  },
  {
    name: 'Omelette',
    category: 'Breakfast & Snacks',
    price: 120,
    isAvailable: true,
    isVeg: false,
    description: 'Fluffy double egg omelette with onions, green chillies & pepper.',
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '8 mins',
  },

  // CURRIES (AUTHENTIC JAFFNA CULINARY ASSETS)
  {
    name: 'Fish Fry',
    category: 'Curries',
    price: 100,
    isAvailable: true,
    isVeg: false,
    description: 'Spicy pan-fried sea fish slice marinated in Jaffna chili paste.',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '12 mins',
  },
  {
    name: 'Fish Curry',
    category: 'Curries',
    price: 150,
    isAvailable: true,
    isVeg: false,
    description: 'Fresh ocean fish cooked in tangy dark coconut gravy.',
    imageUrl: '/images/fish_curry_real.jpg',
    rating: 4.85,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Curry',
    category: 'Curries',
    price: 550,
    isAvailable: true,
    isVeg: false,
    description: 'Tender chicken slow-cooked in rich dark roasted Ceylon curry spices.',
    imageUrl: '/images/chicken_curry_real.jpg',
    rating: 4.95,
    prepTime: '20 mins',
  },
  {
    name: 'Beef Curry',
    category: 'Curries',
    price: 650,
    isAvailable: true,
    isVeg: false,
    description: 'Succulent beef simmered with thick spicy Ceylon gravy.',
    imageUrl: '/images/beef_curry_real.jpg',
    rating: 4.9,
    prepTime: '22 mins',
  },
  {
    name: 'Mutton Curry',
    category: 'Curries',
    price: 700,
    isAvailable: true,
    isVeg: false,
    description: 'Tender mutton slow-cooked in spicy Jaffna claypot curry.',
    imageUrl: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '25 mins',
  },

  // MEALS
  {
    name: 'Veg Meal',
    category: 'Meals',
    price: 300,
    isAvailable: true,
    isVeg: true,
    description: 'Traditional Sri Lankan rice thali served with dahl, 4 vegetable curries & papadam.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Meal',
    category: 'Meals',
    price: 350,
    isAvailable: true,
    isVeg: false,
    description: 'Rice meal platter featuring spiced boiled egg, curries & sambol.',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '15 mins',
  },
  {
    name: 'Fish Meal',
    category: 'Meals',
    price: 400,
    isAvailable: true,
    isVeg: false,
    description: 'Rice meal thali served with sea fish curry, vegetable sides & fried chili.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.88,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Meal',
    category: 'Meals',
    price: 700,
    isAvailable: true,
    isVeg: false,
    description: 'Full rice thali served with roasted chicken curry & vegetable sides.',
    imageUrl: 'https://images.unsplash.com/photo-1617692855027-33b14f061079?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '15 mins',
  },
  {
    name: 'Beef Meal',
    category: 'Meals',
    price: 750,
    isAvailable: true,
    isVeg: false,
    description: 'Hearty rice platter served with dark spicy beef curry & side curries.',
    imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '15 mins',
  },
  {
    name: 'Mutton Meal',
    category: 'Meals',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Pearl Hotel Royal Special thali served with tender mutton curry.',
    imageUrl: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
    rating: 4.98,
    prepTime: '20 mins',
  },

  // SPECIALS & DEVILS
  {
    name: 'Chicken Devilled',
    category: 'Specials & Devils',
    price: 650,
    isAvailable: true,
    isVeg: false,
    description: 'Crispy fried chicken chunks sautéed in sweet & spicy chili pepper sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '18 mins',
  },
  {
    name: 'Prawn Devilled',
    category: 'Specials & Devils',
    price: 700,
    isAvailable: true,
    isVeg: false,
    description: 'Juicy ocean prawns tossed in fiery tomato & chili pepper glaze.',
    imageUrl: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=800&q=80',
    rating: 4.96,
    prepTime: '20 mins',
  },
  {
    name: 'Cuttlefish / Squid Devilled',
    category: 'Specials & Devils',
    price: 700,
    isAvailable: true,
    isVeg: false,
    description: 'Tender squid rings stir-fried with capsicum, onions & spicy pepper sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Beef Devilled',
    category: 'Specials & Devils',
    price: 750,
    isAvailable: true,
    isVeg: false,
    description: 'Seared beef strips tossed with onions & hot spicy chili reduction.',
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },

  // BIRYANI
  {
    name: 'Veg Biryani',
    category: 'Biryani',
    price: 550,
    isAvailable: true,
    isVeg: true,
    description: 'Fragrant basmati rice cooked with fresh vegetables & biryani spices.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '20 mins',
  },
  {
    name: 'Egg Biryani',
    category: 'Biryani',
    price: 600,
    isAvailable: true,
    isVeg: false,
    description: 'Aromatic basmati biryani slow-cooked with boiled egg & raita.',
    imageUrl: '/images/egg_biryani.jpg',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Chicken Biryani',
    category: 'Biryani',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Signature Dum Biryani cooked with succulent spiced chicken leg & boiled egg.',
    imageUrl: '/images/chicken_biryani_handi.jpg',
    rating: 4.98,
    prepTime: '22 mins',
  },
  {
    name: 'Beef Biryani',
    category: 'Biryani',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Spiced basmati biryani cooked with tender beef cuts & fried onions.',
    imageUrl: '/images/beef_fried_rice.jpg',
    rating: 4.95,
    prepTime: '25 mins',
  },

  // RICE TABLE (Half & Full)
  {
    name: 'Veg Rice (Half Portion)',
    category: 'Rice Table',
    price: 400,
    isAvailable: true,
    isVeg: true,
    description: 'Half portion wok-tossed vegetable fried rice.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    rating: 4.75,
    prepTime: '15 mins',
  },
  {
    name: 'Veg Rice (Full Portion)',
    category: 'Rice Table',
    price: 500,
    isAvailable: true,
    isVeg: true,
    description: 'Wok-tossed basmati fried rice with fresh vegetables (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Rice (Half Portion)',
    category: 'Rice Table',
    price: 500,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion scrambled egg fried rice.',
    imageUrl: '/images/egg_fried_rice_real.jpg',
    rating: 4.8,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Rice (Full Portion)',
    category: 'Rice Table',
    price: 700,
    isAvailable: true,
    isVeg: false,
    description: 'Savory fried rice scrambled with fresh farm eggs (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Rice (Half Portion)',
    category: 'Rice Table',
    price: 800,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion wok-fried chicken fried rice.',
    imageUrl: '/images/chicken_fried_rice.jpg',
    rating: 4.9,
    prepTime: '18 mins',
  },
  {
    name: 'Chicken Rice (Full Portion)',
    category: 'Rice Table',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Signature fried rice tossed with juicy roasted chicken pieces (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '18 mins',
  },
  {
    name: 'Beef Rice (Half Portion)',
    category: 'Rice Table',
    price: 900,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion wok-fried rice with spiced beef cuts.',
    imageUrl: '/images/beef_fried_rice.jpg',
    rating: 4.88,
    prepTime: '20 mins',
  },
  {
    name: 'Beef Rice (Full Portion)',
    category: 'Rice Table',
    price: 1100,
    isAvailable: true,
    isVeg: false,
    description: 'Wok-fried rice with tender spiced beef cuts & green onions (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Prawn Rice (Half Portion)',
    category: 'Rice Table',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion fried rice loaded with sea prawns.',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Prawn Rice (Full Portion)',
    category: 'Rice Table',
    price: 1200,
    isAvailable: true,
    isVeg: false,
    description: 'Aromatic fried rice loaded with fresh ocean prawns (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '20 mins',
  },
  {
    name: 'Cuttlefish Rice (Half Portion)',
    category: 'Rice Table',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion fried rice with tender squid rings.',
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Cuttlefish Rice (Full Portion)',
    category: 'Rice Table',
    price: 1200,
    isAvailable: true,
    isVeg: false,
    description: 'Seafood fried rice tossed with seasoned squid rings (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '20 mins',
  },
  {
    name: 'Mixed Rice (Half Portion)',
    category: 'Rice Table',
    price: 1500,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion ultimate mixed fried rice (Chicken, beef, prawns & egg).',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '20 mins',
  },
  {
    name: 'Mixed Rice (Full Portion)',
    category: 'Rice Table',
    price: 1700,
    isAvailable: true,
    isVeg: false,
    description: 'Ultimate mixed fried rice loaded with chicken, beef, prawns & egg (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1543353071-10c8ba85a904?auto=format&fit=crop&w=800&q=80',
    rating: 4.98,
    prepTime: '20 mins',
  },

  // KOTTU TABLE (Half & Full)
  {
    name: 'Veg Kottu (Half Portion)',
    category: 'Kottu Table',
    price: 400,
    isAvailable: true,
    isVeg: true,
    description: 'Half portion shredded godamba roti kottu stir-fried with veggies.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    prepTime: '15 mins',
  },
  {
    name: 'Veg Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 500,
    isAvailable: true,
    isVeg: true,
    description: 'Shredded godamba roti stir-fried with vegetables & spices (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Kottu (Half Portion)',
    category: 'Kottu Table',
    price: 500,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion chopped kottu roti with scrambled egg & gravy.',
    imageUrl: '/images/kottu_handi_real.jpg',
    rating: 4.88,
    prepTime: '15 mins',
  },
  {
    name: 'Egg Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 700,
    isAvailable: true,
    isVeg: false,
    description: 'Chopped roti cooked on flat top with scrambled egg and spicy gravy (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Kottu (Half Portion)',
    category: 'Kottu Table',
    price: 800,
    isAvailable: true,
    isVeg: false,
    description: 'Sizzling godamba roti kottu chopped with chicken pieces & spicy gravy (Half portion).',
    imageUrl: '/images/real_kottu.png',
    rating: 4.95,
    prepTime: '15 mins',
  },
  {
    name: 'Chicken Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Classic Sri Lankan street food chopped roti with roasted chicken & curry gravy (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80',
    rating: 4.99,
    prepTime: '18 mins',
  },
  {
    name: 'Beef Kottu (Half Portion)',
    category: 'Kottu Table',
    price: 850,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion spicy chopped roti with tender beef.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Beef Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1100,
    isAvailable: true,
    isVeg: false,
    description: 'Spicy chopped roti with tender beef, egg & rich beef gravy (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '20 mins',
  },
  {
    name: 'Prawn Kottu (Half Portion)',
    category: 'Kottu Table',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion seafood kottu with fresh prawns.',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '20 mins',
  },
  {
    name: 'Prawn Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1200,
    isAvailable: true,
    isVeg: false,
    description: 'Seafood special kottu chopped with fresh prawns, egg & capsicum (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '20 mins',
  },
  {
    name: 'Cuttlefish Kottu (Half Portion)',
    category: 'Kottu Table',
    price: 1000,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion kottu chopped with ocean squid rings.',
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    prepTime: '20 mins',
  },
  {
    name: 'Cuttlefish Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1200,
    isAvailable: true,
    isVeg: false,
    description: 'Tender squid rings chopped with roti, veggies & seafood sauce (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    prepTime: '20 mins',
  },
  {
    name: 'Mixed Kottu (Half Portion)',
    category: 'Kottu Table',
    price: 1500,
    isAvailable: true,
    isVeg: false,
    description: 'Half portion royal mixed kottu with chicken, beef, prawns & egg.',
    imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    prepTime: '22 mins',
  },
  {
    name: 'Mixed Kottu (Full Portion)',
    category: 'Kottu Table',
    price: 1700,
    isAvailable: true,
    isVeg: false,
    description: 'The supreme royal kottu combining chicken, beef, prawns & egg (Full portion).',
    imageUrl: 'https://images.unsplash.com/photo-1543353071-10c8ba85a904?auto=format&fit=crop&w=800&q=80',
    rating: 4.99,
    prepTime: '22 mins',
  },
];
